/**
 * CI gate: Shared Edge Function utility coverage enforcement.
 *
 * Reads the LCOV coverage report generated by:
 *   deno test --coverage=coverage && deno coverage coverage --lcov > coverage/lcov.info
 *
 * Fails (exit code 1) if branch coverage for any of the 4 shared utilities
 * is below 100%.
 *
 * Run via: deno run --allow-read scripts/check-shared-util-coverage.ts
 */

const REQUIRED_FILES = [
  "_shared/tenant-guard.ts",
  "_shared/audit-logger.ts",
  "_shared/error-response.ts",
  "_shared/cors.ts",
] as const;

const LCOV_PATH = new URL("../supabase/functions/coverage/lcov.info", import.meta.url);

interface FileCoverage {
  file: string;
  linesFound: number;
  linesHit: number;
  branchesFound: number;
  branchesHit: number;
}

function parseLcov(content: string): Map<string, FileCoverage> {
  const result = new Map<string, FileCoverage>();
  let current: Partial<FileCoverage> & { file?: string } = {};

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith("SF:")) {
      current = { file: trimmed.slice(3) };
    } else if (trimmed.startsWith("LF:")) {
      current.linesFound = parseInt(trimmed.slice(3), 10);
    } else if (trimmed.startsWith("LH:")) {
      current.linesHit = parseInt(trimmed.slice(3), 10);
    } else if (trimmed.startsWith("BRF:")) {
      current.branchesFound = parseInt(trimmed.slice(4), 10);
    } else if (trimmed.startsWith("BRH:")) {
      current.branchesHit = parseInt(trimmed.slice(4), 10);
    } else if (trimmed === "end_of_record" && current.file) {
      result.set(current.file, {
        file: current.file,
        linesFound: current.linesFound ?? 0,
        linesHit: current.linesHit ?? 0,
        branchesFound: current.branchesFound ?? 0,
        branchesHit: current.branchesHit ?? 0,
      });
      current = {};
    }
  }
  return result;
}

async function main(): Promise<void> {
  let lcovContent: string;
  try {
    lcovContent = await Deno.readTextFile(LCOV_PATH);
  } catch {
    console.error(
      "❌  coverage/lcov.info not found. Run tests with --coverage first:\n" +
      "    cd supabase/functions && deno task test:coverage",
    );
    Deno.exit(1);
  }

  const coverage = parseLcov(lcovContent);
  let allPassed = true;

  const normalize = (p: string) => p.replace(/\\/g, "/");

  for (const required of REQUIRED_FILES) {
    const entry = [...coverage.entries()].find(([k]) =>
      normalize(k).endsWith(normalize(required)),
    );

    if (!entry) {
      console.error(`❌  No coverage data found for: ${required}`);
      allPassed = false;
      continue;
    }

    const [, cov] = entry;
    const linesPct = cov.linesFound > 0
      ? (cov.linesHit / cov.linesFound) * 100
      : 100;
    const branchPct = cov.branchesFound > 0
      ? (cov.branchesHit / cov.branchesFound) * 100
      : 100;

    const lineFail = linesPct < 100;
    const branchFail = branchPct < 100;

    if (lineFail || branchFail) {
      console.error(
        `❌  ${required}\n` +
        `    Lines:    ${cov.linesHit}/${cov.linesFound} (${linesPct.toFixed(1)}%) — need 100%\n` +
        `    Branches: ${cov.branchesHit}/${cov.branchesFound} (${branchPct.toFixed(1)}%) — need 100%`,
      );
      allPassed = false;
    } else {
      console.log(`✅  ${required} — Lines: 100% | Branches: 100%`);
    }
  }

  if (!allPassed) {
    console.error(
      "\n🚨  Shared utility coverage gate FAILED.\n" +
      "    Epic 2+ stories cannot begin until all 4 shared utilities have 100% coverage.",
    );
    Deno.exit(1);
  }

  console.log("\n✅  All shared utility coverage gates passed. Epic 2 is unblocked.");
}

await main();
