-- =============================================================================
-- Migration: Epic 4 Training Ledger (Story 4.1)
-- 3-Layer Compliance Model:
--   Layer A: training_records (raw LearnDash sync — overwritten on each pull)
--   Layer B: training_adjustments (HR overrides — append-only, immutable)
--   Layer C: v_training_compliance VIEW (effective values — B wins over A)
-- + training_events (immutable audit trail, auto-generated by triggers)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- training_records (Layer A — raw sync from LearnDash)
-- ---------------------------------------------------------------------------

create table if not exists public.training_records (
  id              uuid        primary key default gen_random_uuid(),
  tenant_id       uuid        not null references public.tenants(id),
  person_id       uuid        not null references public.people(id),
  course_id       text        not null,
  course_name     text,
  status          text        check (status in ('not_started', 'in_progress', 'completed')),
  completion_pct  integer,
  completed_at    timestamptz,
  training_hours  integer,                -- minutes, from LearnDash
  expires_at      timestamptz,            -- certification expiry (future use)
  last_synced_at  timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on table public.training_records is
  'Layer A: Raw training data synced from LearnDash. Sync overwrites on each pull. Never contains HR overrides.';

comment on column public.training_records.training_hours is
  'Training duration in minutes. Synced from LearnDash.';

comment on column public.training_records.expires_at is
  'Certification expiry date. Nullable — used for future expiration detection.';

-- Dedup: one record per person per course per tenant
create unique index training_records_tenant_person_course_idx
  on public.training_records (tenant_id, person_id, course_id);

-- RLS: own tenant — SELECT, INSERT, UPDATE allowed (sync needs UPDATE)
alter table public.training_records enable row level security;

create policy "training_records_own_tenant" on public.training_records
  using (
    tenant_id = ((auth.jwt() -> 'app_metadata' ->> 'tenant_id')::uuid)
  );

-- ---------------------------------------------------------------------------
-- training_adjustments (Layer B — HR overrides, append-only)
-- ---------------------------------------------------------------------------

create table if not exists public.training_adjustments (
  id              uuid        primary key default gen_random_uuid(),
  tenant_id       uuid        not null references public.tenants(id),
  person_id       uuid        not null references public.people(id),
  course_id       text        not null,
  field           text        not null
                              check (field in ('status', 'completion_pct', 'completed_at', 'training_hours')),
  value           text        not null,
  reason          text        not null,
  actor_id        uuid        not null references auth.users(id),
  created_at      timestamptz not null default now()
);

comment on table public.training_adjustments is
  'Layer B: HR overrides for training compliance. Append-only — no UPDATE or DELETE. Latest override per (person_id, course_id, field) wins.';

comment on column public.training_adjustments.field is
  'Which training_records field is being overridden. CHECK constraint enforces valid values.';

comment on column public.training_adjustments.reason is
  'Required justification for the override. Compliance audit trail.';

-- RLS: INSERT + SELECT for own tenant. NO UPDATE. NO DELETE.
alter table public.training_adjustments enable row level security;

create policy "training_adjustments_select_own" on public.training_adjustments
  for select
  using (
    tenant_id = ((auth.jwt() -> 'app_metadata' ->> 'tenant_id')::uuid)
  );

create policy "training_adjustments_insert_own" on public.training_adjustments
  for insert
  with check (
    tenant_id = ((auth.jwt() -> 'app_metadata' ->> 'tenant_id')::uuid)
  );

-- No UPDATE policy -> UPDATE denied for all roles
-- No DELETE policy -> DELETE denied for all roles

-- ---------------------------------------------------------------------------
-- training_events (immutable audit trail for training actions)
-- ---------------------------------------------------------------------------

create table if not exists public.training_events (
  id              uuid        primary key default gen_random_uuid(),
  tenant_id       uuid        not null references public.tenants(id),
  person_id       uuid        not null references public.people(id),
  course_id       text,
  event_type      text        not null
                              check (event_type in ('enrolled', 'completed', 'expired', 'adjusted')),
  payload         jsonb,
  created_at      timestamptz not null default now()
);

comment on table public.training_events is
  'Immutable training event log. Auto-generated by DB triggers. INSERT-only — no UPDATE or DELETE.';

-- RLS: INSERT + SELECT for own tenant. NO UPDATE. NO DELETE.
alter table public.training_events enable row level security;

create policy "training_events_select_own" on public.training_events
  for select
  using (
    tenant_id = ((auth.jwt() -> 'app_metadata' ->> 'tenant_id')::uuid)
  );

create policy "training_events_insert_own" on public.training_events
  for insert
  with check (
    tenant_id = ((auth.jwt() -> 'app_metadata' ->> 'tenant_id')::uuid)
  );

-- No UPDATE policy -> UPDATE denied for all roles
-- No DELETE policy -> DELETE denied for all roles

-- ---------------------------------------------------------------------------
-- Audit triggers (NFR-4: every write emits to audit_log)
-- ---------------------------------------------------------------------------

-- training_records audit
create or replace function public.audit_training_records()
returns trigger language plpgsql security definer as $$
begin
  insert into public.audit_log (
    tenant_id, actor_id, action, table_name, record_id, before, after
  ) values (
    coalesce(new.tenant_id, old.tenant_id),
    (auth.jwt() ->> 'sub')::uuid,
    tg_op,
    'training_records',
    coalesce(new.id, old.id),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );
  return coalesce(new, old);
end;
$$;

create trigger audit_training_records_trigger
  after insert or update on public.training_records
  for each row execute function public.audit_training_records();

-- training_adjustments audit
create or replace function public.audit_training_adjustments()
returns trigger language plpgsql security definer as $$
begin
  insert into public.audit_log (
    tenant_id, actor_id, action, table_name, record_id, before, after
  ) values (
    new.tenant_id,
    (auth.jwt() ->> 'sub')::uuid,
    tg_op,
    'training_adjustments',
    new.id,
    null,           -- append-only: no old row
    to_jsonb(new)
  );
  return new;
end;
$$;

create trigger audit_training_adjustments_trigger
  after insert on public.training_adjustments
  for each row execute function public.audit_training_adjustments();

-- training_events audit
create or replace function public.audit_training_events()
returns trigger language plpgsql security definer as $$
begin
  insert into public.audit_log (
    tenant_id, actor_id, action, table_name, record_id, before, after
  ) values (
    new.tenant_id,
    (auth.jwt() ->> 'sub')::uuid,
    tg_op,
    'training_events',
    new.id,
    null,           -- insert-only: no old row
    to_jsonb(new)
  );
  return new;
end;
$$;

create trigger audit_training_events_trigger
  after insert on public.training_events
  for each row execute function public.audit_training_events();

-- ---------------------------------------------------------------------------
-- Event-generating triggers (auto-populate training_events)
-- ---------------------------------------------------------------------------

-- On training_records INSERT -> 'enrolled' event
-- On training_records UPDATE where status changed to 'completed' -> 'completed' event
create or replace function public.training_records_event_trigger()
returns trigger language plpgsql security definer as $$
begin
  if tg_op = 'INSERT' then
    insert into public.training_events (tenant_id, person_id, course_id, event_type, payload)
    values (
      new.tenant_id,
      new.person_id,
      new.course_id,
      'enrolled',
      jsonb_build_object(
        'course_name', new.course_name,
        'source', 'learndash_sync'
      )
    );
  elsif tg_op = 'UPDATE'
    and new.status = 'completed'
    and (old.status is distinct from 'completed')
  then
    insert into public.training_events (tenant_id, person_id, course_id, event_type, payload)
    values (
      new.tenant_id,
      new.person_id,
      new.course_id,
      'completed',
      jsonb_build_object(
        'course_name', new.course_name,
        'completed_at', new.completed_at,
        'completion_pct', new.completion_pct,
        'source', 'learndash_sync'
      )
    );
  end if;
  return new;
end;
$$;

create trigger training_records_event
  after insert or update on public.training_records
  for each row execute function public.training_records_event_trigger();

-- On training_adjustments INSERT -> 'adjusted' event
create or replace function public.training_adjustments_event_trigger()
returns trigger language plpgsql security definer as $$
begin
  insert into public.training_events (tenant_id, person_id, course_id, event_type, payload)
  values (
    new.tenant_id,
    new.person_id,
    new.course_id,
    'adjusted',
    jsonb_build_object(
      'field', new.field,
      'value', new.value,
      'reason', new.reason,
      'actor_id', new.actor_id
    )
  );
  return new;
end;
$$;

create trigger training_adjustments_event
  after insert on public.training_adjustments
  for each row execute function public.training_adjustments_event_trigger();

-- ---------------------------------------------------------------------------
-- v_training_compliance (Layer C — computed effective values)
-- RLS inherited from underlying tables — no additional policy needed.
-- ---------------------------------------------------------------------------

create or replace view public.v_training_compliance as
with latest_adjustments as (
  select distinct on (tenant_id, person_id, course_id, field)
    tenant_id,
    person_id,
    course_id,
    field,
    value,
    created_at as adjusted_at
  from public.training_adjustments
  order by tenant_id, person_id, course_id, field, created_at desc
),
pivoted as (
  select
    tenant_id,
    person_id,
    course_id,
    max(case when field = 'status' then value end)          as adj_status,
    max(case when field = 'completion_pct' then value end)  as adj_completion_pct,
    max(case when field = 'completed_at' then value end)    as adj_completed_at,
    max(case when field = 'training_hours' then value end)  as adj_training_hours,
    max(adjusted_at)                                         as last_adjusted_at
  from latest_adjustments
  group by tenant_id, person_id, course_id
)
select
  tr.id              as training_record_id,
  tr.tenant_id,
  tr.person_id,
  tr.course_id,
  tr.course_name,
  -- Effective values: Layer B wins over Layer A
  coalesce(p.adj_status, tr.status)                          as effective_status,
  coalesce(p.adj_completion_pct::integer, tr.completion_pct) as effective_completion_pct,
  coalesce(p.adj_completed_at::timestamptz, tr.completed_at) as effective_completed_at,
  coalesce(p.adj_training_hours::integer, tr.training_hours) as effective_training_hours,
  -- Raw Layer A values (for reference/comparison)
  tr.status              as raw_status,
  tr.completion_pct      as raw_completion_pct,
  tr.completed_at        as raw_completed_at,
  tr.training_hours      as raw_training_hours,
  -- Metadata
  tr.expires_at,
  tr.last_synced_at,
  p.last_adjusted_at,
  (p.adj_status is not null
   or p.adj_completion_pct is not null
   or p.adj_completed_at is not null
   or p.adj_training_hours is not null)  as has_overrides
from public.training_records tr
left join pivoted p
  on  p.tenant_id = tr.tenant_id
  and p.person_id = tr.person_id
  and p.course_id = tr.course_id;

comment on view public.v_training_compliance is
  'Layer C: Effective training compliance values. Latest HR override (Layer B) wins over raw sync data (Layer A). Query this view for all compliance reporting.';
